org.gradle.jvmargs=-Xmx3G -Dnet.minecraftforge.gradle.check.certs=false
systemProp.net.minecraftforge.gradle.check.certs=false
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.3.0
forge_version_range=[47.3.0,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=wintercore
mod_name=Fimbulwinter Core (Spore Addon)
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.harbinger.wintercore
mod_authors=Harbinger
mod_description=An independent addon for the Spore mod that introduces the Fimbulwinter beacon to suppress infections.
